macro(set_compiler_flags)

    # Nullify all the Fortran flags
    set(CMAKE_Fortran_FLAGS "")
    set(CMAKE_Fortran_FLAGS_DEBUG "")
    set(CMAKE_Fortran_FLAGS_RELEASE "")

    get_filename_component(COMPILER_NAME ${CMAKE_Fortran_COMPILER} NAME_WE)

    # Covers Windows
    if(WIN32)
        # Windows + ifort
        if(COMPILER_NAME STREQUAL ifort)
            set(CMAKE_Fortran_FLAGS "/W1 /nologo /fpp /threads /Qdiag-disable:10448 /heap-arrays")
            # Windows + ifort + Debug
            if(CMAKE_BUILD_TYPE STREQUAL Debug)
                if (MD)
                    set(CMAKE_Fortran_FLAGS_DEBUG "/debug:full /libs:dll /traceback /Qopt-report=0")
                else()
                    set(CMAKE_Fortran_FLAGS_DEBUG "/debug:full /libs:static /traceback /Qopt-report=0")
                endif()
                set(OPT_FLAGS0 "/Od /check:noarg_temp_created ")
                set(OPT_FLAGS  "/Od /check:noarg_temp_created ")
                set(OPT_FLAGS1 "/Od /check:noarg_temp_created ")
                set(OPT_FLAGS2 "/Od /check:noarg_temp_created ")
                set(OPT_FLAGS3 "/Od /check:noarg_temp_created ")
            # Windows + ifort + Release
            elseif(CMAKE_BUILD_TYPE STREQUAL Release)
                if (MD)
                    set(CMAKE_Fortran_FLAGS_RELEASE "/libs:dll /Qopt-report=0")
                else()
                    set(CMAKE_Fortran_FLAGS_RELEASE "/libs:static /Qopt-report=0")
                endif()
                if (QPARALLEL)
                    set(OPT_FLAGS0 "/Od")
                    set(OPT_FLAGS  "/O2 /Qparallel")
                    set(OPT_FLAGS1 "/O1")
                    set(OPT_FLAGS2 "/O2 /Qparallel")
                    set(OPT_FLAGS3 "/O3 /Qparallel")
                else()
                    set(OPT_FLAGS0 "/Od")
                    set(OPT_FLAGS  "/O2")
                    set(OPT_FLAGS1 "/O1")
                    set(OPT_FLAGS2 "/O2")
                    set(OPT_FLAGS3 "/O3")
                endif()
            endif()
        # Windows + ifx
        elseif(COMPILER_NAME STREQUAL ifx)
            set(CMAKE_Fortran_FLAGS "/nologo /fpp /threads /heap-arrays")
            set(OPT_FLAGS2 "/fpp /Qopt-report:0")
            # Windows + ifx + Debug
            if(CMAKE_BUILD_TYPE STREQUAL Debug)
                set(OPT_FLAGS "/nologo")
                set(OPT_FLAGS0 "/Od")
                set(OPT_FLAGS1 "/debug:full /check /check:noarg_temp_created /traceback /Warn")
                if (MD)
                    set(CMAKE_Fortran_FLAGS_DEBUG "/libs:dll")
                else()
                    set(CMAKE_Fortran_FLAGS_DEBUG "/libs:static")
                endif()
            # Windows + ifx + Release
            elseif(CMAKE_BUILD_TYPE STREQUAL Release)
                set(OPT_FLAGS "/nologo")
                set(OPT_FLAGS0 "/Od")
                set(OPT_FLAGS1 "/O2")
                if (MD)
                    set(CMAKE_Fortran_FLAGS_RELEASE "/libs:dll /heap-arrays")
                else()
                    set(CMAKE_Fortran_FLAGS_RELEASE "/libs:static /heap-arrays")
                endif()
            endif()
        # Windows + gfortran
        elseif(COMPILER_NAME STREQUAL gfortran)
            set(CMAKE_Fortran_FLAGS "-std=f2008 -ffree-line-length-0 -fdec-math -fall-intrinsics -fPIC -frecursive -cpp")
            set(OPT_FLAGSC "-m64")
            set(OPT_FLAGS2 "")
            # Windows + gfortran + Debug
            if(CMAKE_BUILD_TYPE STREQUAL Debug)
                set(OPT_FLAGS0 "-O0 -fcheck=all -finit-real=snan -finit-integer=-999  -Wall 
                    -Wno-maybe-uninitialized -Wno-conversion -Wno-character-truncation -fbacktrace")
                set(OPT_FLAGS1 "-O0 -fcheck=all -finit-real=snan -finit-integer=-999  -Wall 
                    -Wno-maybe-uninitialized -Wno-conversion -Wno-character-truncation -fbacktrace")
            # Windows + gfortran + Release
            elseif(CMAKE_BUILD_TYPE STREQUAL Release)
                set(OPT_FLAGS0 "-O0")
                set(OPT_FLAGS1 "-O0")
            endif()
        endif()
    # Covers Linux and macOS
    # Flags are minimal here and should be updated (notably on optimization)
    elseif(UNIX)
        # Unix + ifort
        if(COMPILER_NAME STREQUAL ifort)
            # Unix + ifort + Debug
            set(CMAKE_Fortran_FLAGS "-cpp -fPIC -heap-arrays -diag-disable=10448")
            if(CMAKE_BUILD_TYPE STREQUAL Debug)
                set(CMAKE_Fortran_FLAGS_DEBUG "-g -warn")
                set(OPT_FLAGS "")
                set(OPT_FLAGS0 "")
                set(OPT_FLAGS1 "")
            # Unix + ifort + Release
            elseif(CMAKE_BUILD_TYPE STREQUAL Release)
                set(CMAKE_Fortran_FLAGS_RELEASE "-warn")
                set(OPT_FLAGS0 "-O0")
                set(OPT_FLAGS1 "-O2")
            endif()
        # Unix + ifx
        elseif(COMPILER_NAME STREQUAL ifx)
            set(CMAKE_Fortran_FLAGS "-cpp -fPIC -heap-arrays")
            if(CMAKE_BUILD_TYPE STREQUAL Debug)
                # Unix + ifx + Debug
                set(CMAKE_Fortran_FLAGS_DEBUG "-g -O0 -check bounds -traceback -warn")
                set(OPT_FLAGS0 "-O0")
                set(OPT_FLAGS1 "")
            # Unix + ifx + Release
            elseif(CMAKE_BUILD_TYPE STREQUAL Release)
                set(CMAKE_Fortran_FLAGS_RELEASE "-warn")
                set(OPT_FLAGS0 "-O0")
                set(OPT_FLAGS1 "-O2")
            endif()
        # Unix + gfortran
        elseif(COMPILER_NAME STREQUAL gfortran)
            set(CMAKE_Fortran_FLAGS "-cpp -std=f2008 -ffree-line-length-none -fPIC -fdec-math -fall-intrinsics -frecursive")
            set(OPT_FLAGSC "-m64")
            # Unix + gfortran + Debug
            if(CMAKE_BUILD_TYPE STREQUAL Debug)
                set(CMAKE_Fortran_FLAGS_DEBUG "-g -O0 -fcheck=all -finit-real=snan -finit-integer=-999 -Wall -Wno-maybe-uninitialized -Wno-conversion -Wno-character-truncation -fbacktrace")
                set(OPT_FLAGS0 "-O0")
                set(OPT_FLAGS1 "-O0")
            # Unix + gfortran + Release
            elseif(CMAKE_BUILD_TYPE STREQUAL Release)
                set(CMAKE_Fortran_FLAGS_RELEASE "")
                set(OPT_FLAGS0 "-O0")
                set(OPT_FLAGS1 "-O0")
            endif()
        endif()
    endif()
endmacro()
