name: debug-build-and-test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  #schedule:
  #  - cron: '*/120 8-18 * * *'  # every 2 hours from 8:00 to 18:00 every day

jobs:

  ##############################################################################
  # JOB 1
  ##############################################################################
  build:  # current job name

    timeout-minutes: 30

    # current job matrix. if modified, remember to UPDATE the strategy in the next job
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-14]
        toolchain:
          - { exe: gfortran, compiler: gcc, version: 13 }
          - { exe: ifx, compiler: intel, version: "2025.2" }
        exclude:
          - os: macos-14
            toolchain: { exe: ifx, compiler: intel, version: "2025.2" } # no support for macOS on arm64

    runs-on: ${{ matrix.os }}

    steps: # job steps
      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history with tags is required for versioningit

      - name: Set up Fortran compiler (FC) [all except Windows + gfortran] # except: use pre-installed gfortran
        if: runner.os != 'Windows' || matrix.toolchain.exe != 'gfortran'
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Set up NMake build tool [Windows]
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Upgrade package installer for Python
        shell: bash
        run: python -m pip install --upgrade pip

      - name: Install Python dependences
        shell: bash
        run: pip install '.[ci,test]'  # 'ci' and 'test' extras from pyproject.toml

      - name: Fix reinstalling gcc [macOS]  # needed because of `brew reinstall gcc`
        if: runner.os == 'macOS'
        shell: bash
        run: echo "MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion)" >> $GITHUB_ENV

      - name: Create build scripts in scripts/scripts
        shell: bash
        run: >
          python3 pybuild.py
          --create-scripts
          --platform ${{ runner.os }}
          --compiler ${{ matrix.toolchain.exe }}
          --mode debug
          --bash-syntax
          --enable-backslash-escapes

      - name: Build CFML and prepare distribution
        shell: bash
        run: scripts/cfml_build.sh

      - name: Run CFML test programs
        shell: bash
        run: scripts/cfml_test.sh

      - name: Resolve wheel directory
        id: wheel_dir
        shell: bash
        run: echo "value=$(python3 pybuild.py --print-wheel-dir)" >> "$GITHUB_OUTPUT"

      - name: Build pyCFML and create wheel
        shell: bash
        run: scripts/pycfml_build.sh

      - name: Fix Python package wheel dependencies
        if: runner.os == 'macOS'
        shell: bash
        run: |
          pip install delocate
          #delocate-wheel -v ${{ steps.wheel_dir.outputs.value }}/*.whl

      - name: Test built pyCFML wheel
        shell: bash
        run: scripts/pycfml_test.sh

      - name: Prepare for uploading Python package wheel of pyCFML
        shell: bash
        run: echo "WHEEL_DIR=$(python3 pybuild.py --print-wheel-dir)" >> $GITHUB_ENV

      - name: Upload zipped Python package wheel of pyCFML for next job
        uses: actions/upload-artifact@v4
        with:  # if name or path modified, remember to UPDATE those in the download step of the next job
          name: pycfml-wheel_${{ matrix.os }}_${{ matrix.toolchain.exe }} # name (without .zip) of the zip file to be uploaded
          path: ${{ steps.wheel_dir.outputs.value }}  # all files in this directory will be zipped
          if-no-files-found: "error"
          compression-level: 0

  ##############################################################################
  # JOB 2
  ##############################################################################
  test:  # current job name

    needs: build  # previous job 'build' need to be finished first

    if: always()  # start this job even if the previous job failed

    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-14]
        toolchain:
          - { exe: gfortran, compiler: gcc, version: 13 }
          - { exe: ifx, compiler: intel, version: "2025.2" }
        exclude:
          - os: macos-14
            toolchain: { exe: ifx, compiler: intel, version: "2025.2" } # no support for macOS on arm64

    runs-on: ${{ matrix.os }}

    steps:  # job steps
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Upgrade package installer for Python
        shell: bash
        run: python3 -m pip install --upgrade pip

      - name: Install Python dependences
        shell: bash
        run: pip install '.[ci,test]'  # 'ci' and 'test' extras from pyproject.toml

      - name: Create job step scripts
        shell: bash
        run: >
          python3 pybuild.py
          --create-scripts
          --platform ${{ runner.os }}
          --compiler ${{ matrix.toolchain.exe }}
          --mode debug
          --bash-syntax
          --enable-backslash-escapes

      - name: Resolve wheel directory
        id: wheel_dir
        shell: bash
        run: echo "value=$(python3 pybuild.py --print-wheel-dir)" >> "$GITHUB_OUTPUT"

      - name: Download zipped pyCFML wheel from previous job
        uses: actions/download-artifact@v4
        with:  # name or path are taken from the upload step of the previous job
          name: pycfml-wheel_${{ matrix.os }}_${{ matrix.toolchain.exe }}  # name (without .zip) of the zipped artifact uploaded on the previous jobs
          path: ${{ steps.wheel_dir.outputs.value }}  # directory to extract downloaded zipped artifacts

      - name: Test downloaded pyCFML wheel
        shell: bash
        run: scripts/pycfml_test.sh
